//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class alcool
    {
        public string NOM_ALCOOL { get; set; }
        public int NUM_ALCOOL { get; set; }
        public Nullable<float> DEGRE { get; set; }
    }
}
