//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isi_projet2_tardymartial_remondvictorEntities : DbContext
    {
        public isi_projet2_tardymartial_remondvictorEntities()
            : base("name=isi_projet2_tardymartial_remondvictorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alcool> alcool { get; set; }
        public DbSet<cocktail> cocktail { get; set; }
        public DbSet<etaperecette> etaperecette { get; set; }
        public DbSet<ingredientalcool> ingredientalcool { get; set; }
        public DbSet<ingredientsoft> ingredientsoft { get; set; }
        public DbSet<soft> soft { get; set; }
    }
}
