//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cocktail
    {
        public string NOM_COCKTAIL { get; set; }
        public int NUM_COCKTAIL { get; set; }
        public string IMG { get; set; }
        public int TAILLE { get; set; }

        public new string ToString()
        {
            return "N°" + NUM_COCKTAIL + " : " + NOM_COCKTAIL + ", " + TAILLE + "mL";
        }
    }
}
