//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class cocktail
    {
        public string NOM_COCKTAIL { get; set; }
        public int NUM_COCKTAIL { get; set; }
        public string IMG { get; set; }
        public int TAILLE { get; set; }
    }
}
