//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CocktailsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredientalcool
    {
        public int NUM_COCKTAIL { get; set; }
        public int NUM_ALCOOL { get; set; }
        public int QUANTITE { get; set; }
    }
}
